modLoader="javafml"
loaderVersion="[47,)"
license="MIT"
[[mods]]
modId="spacetravel"
version="0.2.0"
displayName="Space Travel"
credits=""
authors="Povstalec"
displayTest="MATCH_VERSION"

description='''Space Travel'''
[[dependencies.spacetravel]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.spacetravel]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="BOTH"

[[dependencies.spacetravel]]
modId="stellarview"
mandatory=true
versionRange="[0.4.1,0.5.0)"
ordering="NONE"
side="BOTH"